[build]
command = """
  if [ ! -d flutter ]; then
    git clone --depth 1 --branch 3.22.2 https://github.com/flutter/flutter.git
  else
    cd flutter && git fetch --tags && git checkout 3.22.2 && cd ..
  fi
  flutter/bin/flutter config --enable-web
  flutter/bin/flutter --version
  flutter/bin/flutter pub get --enforce-lockfile
  flutter/bin/flutter build web --release --no-wasm-dry-run
  """
publish = "build/web"
